import { adminDb } from "../lib/firebase-admin";
import { FieldValue } from "firebase-admin/firestore";
const reports = [
    {
        title: "Large pothole near Sector 17",
        description: "A deep pothole is causing traffic delays and damaging vehicles.",
        location: "Sector 17, Chandigarh",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Critical",
        priorityScore: 95,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 18,
        resolvedVotes: 1,
    },

    {
        title: "Water leakage outside market",
        description: "Continuous leakage from an underground pipeline.",
        location: "Sector 22 Market, Chandigarh",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "High",
        priorityScore: 90,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 12,
        resolvedVotes: 0,
    },

    {
        title: "Broken street light",
        description: "The entire street remains dark after sunset.",
        location: "IIT Ropar Main Gate",
        category: "Electricity",
        department: "Electricity Department",
        severity: "Medium",
        priorityScore: 72,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 6,
        resolvedVotes: 0,

    },

    {
        title: "Large pothole causing traffic delays",
        description: "A deep pothole in the middle of the road is slowing traffic and creating a risk for two-wheelers.",
        location: "Sector 17, Chandigarh",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "High",
        priorityScore: 84,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 19,
        resolvedVotes: 0
    },
    {
        title: "Burst water pipeline flooding street",
        description: "A damaged underground pipeline is flooding the road and wasting clean water.",
        location: "Sector 70, Mohali",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Critical",
        priorityScore: 96,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 41,
        resolvedVotes: 0
    },
    {
        title: "Garbage overflowing from community bins",
        description: "Garbage bins have not been cleared for several days, attracting stray animals.",
        location: "Model Town, Ropar",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "Medium",
        priorityScore: 69,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 14,
        resolvedVotes: 1
    },
    {
        title: "Street lights not functioning",
        description: "Several street lights have stopped working, making the road unsafe at night.",
        location: "Dwarka Sector 10, Delhi",
        category: "Electricity",
        department: "Electricity Department",
        severity: "High",
        priorityScore: 82,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 26,
        resolvedVotes: 2
    },
    {
        title: "Broken traffic signal at intersection",
        description: "Traffic signal has remained non-functional since morning, causing congestion.",
        location: "Vaishali Nagar, Jaipur",
        category: "Public Safety",
        department: "Police Department",
        severity: "Critical",
        priorityScore: 94,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 37,
        resolvedVotes: 0
    },
    {
        title: "Uneven footpath posing trip hazard",
        description: "Damaged pavement slabs are creating safety hazards for pedestrians.",
        location: "DLF Phase 3, Gurugram",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Medium",
        priorityScore: 65,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 9,
        resolvedVotes: 0
    },
    {
        title: "Low water pressure in residential area",
        description: "Residents are experiencing insufficient water pressure during morning hours.",
        location: "Sector 22, Chandigarh",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Medium",
        priorityScore: 71,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 22,
        resolvedVotes: 0
    },
    {
        title: "Open garbage dump near school",
        description: "Waste is scattered around an open dumping site close to a school entrance.",
        location: "Phase 7, Mohali",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "High",
        priorityScore: 81,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 31,
        resolvedVotes: 0
    },
    {
        title: "Frequent power outages",
        description: "Electricity supply has been interrupted multiple times throughout the day.",
        location: "Bela Chowk, Ropar",
        category: "Electricity",
        department: "Electricity Department",
        severity: "High",
        priorityScore: 86,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 28,
        resolvedVotes: 3
    },
    {
        title: "Damaged CCTV camera",
        description: "The public surveillance camera at the junction is not operational.",
        location: "Karol Bagh, Delhi",
        category: "Public Safety",
        department: "Police Department",
        severity: "Medium",
        priorityScore: 68,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 13,
        resolvedVotes: 1
    },
    {
        title: "Road shoulder collapsing",
        description: "The edge of the road has eroded, making it dangerous for vehicles.",
        location: "Malviya Nagar, Jaipur",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Critical",
        priorityScore: 92,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 36,
        resolvedVotes: 0
    },
    {
        title: "Water leakage near market",
        description: "Continuous leakage from a pipeline is causing waterlogging.",
        location: "Sector 56, Gurugram",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "High",
        priorityScore: 83,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 20,
        resolvedVotes: 0
    },
    {
        title: "Overflowing public dustbins",
        description: "Dustbins have exceeded capacity and waste is spilling onto the road.",
        location: "Sector 35, Chandigarh",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "Medium",
        priorityScore: 67,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 15,
        resolvedVotes: 0
    },
    {
        title: "Transformer emitting sparks",
        description: "Residents observed sparks from a roadside transformer.",
        location: "Sector 115, Mohali",
        category: "Electricity",
        department: "Electricity Department",
        severity: "Critical",
        priorityScore: 98,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 49,
        resolvedVotes: 0
    },
    {
        title: "Abandoned vehicle blocking lane",
        description: "An abandoned vehicle has occupied one lane for over a week.",
        location: "Connaught Place, Delhi",
        category: "Public Safety",
        department: "Police Department",
        severity: "Medium",
        priorityScore: 70,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 18,
        resolvedVotes: 2
    },
    {
        title: "Cracked road surface",
        description: "Long cracks have developed across the main road.",
        location: "Sector 15, Chandigarh",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Medium",
        priorityScore: 63,
        status: "Resolved",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 8,
        resolvedVotes: 11
    },
    {
        title: "Contaminated drinking water complaint",
        description: "Residents reported muddy water coming from household taps.",
        location: "Sector 68, Mohali",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Critical",
        priorityScore: 97,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 53,
        resolvedVotes: 0
    },
    {
        title: "Garbage burning in open area",
        description: "Waste is being burned in the open, causing heavy smoke.",
        location: "Railway Road, Ropar",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "High",
        priorityScore: 88,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 25,
        resolvedVotes: 1
    },
    {
        title: "Loose hanging power cable",
        description: "A low-hanging electrical cable poses danger to pedestrians.",
        location: "Lajpat Nagar, Delhi",
        category: "Electricity",
        department: "Electricity Department",
        severity: "Critical",
        priorityScore: 95,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 44,
        resolvedVotes: 0
    },
    {
        title: "Street harassment hotspot",
        description: "Residents reported repeated harassment incidents during late evening.",
        location: "Mansarovar, Jaipur",
        category: "Public Safety",
        department: "Police Department",
        severity: "High",
        priorityScore: 87,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 34,
        resolvedVotes: 2
    },
    {
        title: "Damaged speed breaker",
        description: "The speed breaker has worn out and is barely visible.",
        location: "Sector 45, Gurugram",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Low",
        priorityScore: 48,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 5,
        resolvedVotes: 0
    },
    {
        title: "Public tap leaking continuously",
        description: "A roadside public tap has been leaking for several days.",
        location: "Sector 43, Chandigarh",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Low",
        priorityScore: 45,
        status: "Resolved",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 4,
        resolvedVotes: 7
    },
    {
        title: "Illegal dumping of construction debris",
        description: "Construction waste has been dumped beside the road.",
        location: "Aerocity, Mohali",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "Medium",
        priorityScore: 66,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 12,
        resolvedVotes: 0
    },
    {
        title: "Streetlight flickering repeatedly",
        description: "Streetlights keep flickering throughout the night.",
        location: "Civil Lines, Ropar",
        category: "Electricity",
        department: "Electricity Department",
        severity: "Medium",
        priorityScore: 64,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 10,
        resolvedVotes: 1
    },
    {
        title: "Broken pedestrian crossing signal",
        description: "The pedestrian signal remains red permanently.",
        location: "Saket, Delhi",
        category: "Public Safety",
        department: "Police Department",
        severity: "Medium",
        priorityScore: 72,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 16,
        resolvedVotes: 0
    },
    {
        title: "Sunken manhole on roadway",
        description: "A sunken manhole cover is damaging passing vehicles.",
        location: "C-Scheme, Jaipur",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "High",
        priorityScore: 85,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 29,
        resolvedVotes: 2
    },
    {
        title: "No water supply since morning",
        description: "Residents have not received water due to maintenance issues.",
        location: "Sector 46, Gurugram",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "High",
        priorityScore: 89,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 32,
        resolvedVotes: 0
    },
    {
        title: "Uncollected waste near park",
        description: "Household waste has accumulated around the public park.",
        location: "Sector 21, Chandigarh",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "Medium",
        priorityScore: 62,
        status: "Resolved",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 11,
        resolvedVotes: 14
    },
    {
        title: "Power transformer oil leakage",
        description: "Transformer appears to be leaking oil onto the roadside.",
        location: "Kharar Road, Mohali",
        category: "Electricity",
        department: "Electricity Department",
        severity: "High",
        priorityScore: 91,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 35,
        resolvedVotes: 0
    },
    {
        title: "Suspicious abandoned bag reported",
        description: "An unattended bag has been left near the bus stop.",
        location: "Rajouri Garden, Delhi",
        category: "Public Safety",
        department: "Police Department",
        severity: "Critical",
        priorityScore: 93,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 40,
        resolvedVotes: 0
    },
    {
        title: "Broken divider barriers",
        description: "Concrete divider barriers are damaged after a collision.",
        location: "Jagatpura, Jaipur",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "High",
        priorityScore: 80,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 21,
        resolvedVotes: 1
    },
    {
        title: "Waterlogging after light rain",
        description: "Poor drainage has caused water accumulation on the road.",
        location: "Golf Course Road, Gurugram",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Medium",
        priorityScore: 73,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 19,
        resolvedVotes: 2
    },
    {
        title: "Overflowing garbage near bus stand",
        description: "Garbage has piled up beside the public bus stand.",
        location: "Bus Stand Road, Ropar",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "High",
        priorityScore: 79,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 24,
        resolvedVotes: 0
    },
    {
        title: "Voltage fluctuations damaging appliances",
        description: "Frequent voltage fluctuations are affecting residential homes.",
        location: "Sector 14, Chandigarh",
        category: "Electricity",
        department: "Electricity Department",
        severity: "High",
        priorityScore: 90,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 30,
        resolvedVotes: 1
    },
    {
        title: "Poor lighting in public park",
        description: "The park remains dark after sunset due to missing lights.",
        location: "Sector 62, Mohali",
        category: "Public Safety",
        department: "Police Department",
        severity: "Medium",
        priorityScore: 61,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 9,
        resolvedVotes: 0
    },
    {
        title: "Road markings faded",
        description: "Lane markings have faded, confusing motorists.",
        location: "Ashok Vihar, Delhi",
        category: "Roads & Pavement",
        department: "Public Works Department",
        severity: "Low",
        priorityScore: 50,
        status: "Resolved",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 6,
        resolvedVotes: 9
    },
    {
        title: "Broken water valve near colony",
        description: "A damaged valve is leaking water continuously.",
        location: "Tonk Road, Jaipur",
        category: "Water Supply",
        department: "Water Management Department",
        severity: "Medium",
        priorityScore: 74,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 17,
        resolvedVotes: 0
    },
    {
        title: "Garbage collection skipped for a week",
        description: "Residents report no garbage pickup for seven days.",
        location: "Sector 57, Gurugram",
        category: "Garbage Management",
        department: "Sanitation Department",
        severity: "High",
        priorityScore: 78,
        status: "In Progress",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 27,
        resolvedVotes: 1
    },
    {
        title: "Electric pole leaning dangerously",
        description: "The electric pole appears tilted after heavy rainfall.",
        location: "Sector 18, Chandigarh",
        category: "Electricity",
        department: "Electricity Department",
        severity: "Critical",
        priorityScore: 99,
        status: "Pending",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 52,
        resolvedVotes: 0
    },
    {
        title: "Missing manhole cover",
        description: "An uncovered manhole presents a serious risk to pedestrians and vehicles.",
        location: "MG Road, Gurugram",
        category: "Public Safety",
        department: "Police Department",
        severity: "Critical",
        priorityScore: 97,
        status: "Assigned",
        latitude: null,
        longitude: null,
        imageUrl: "",
        confirmVotes: 47,
        resolvedVotes: 0
    }

];
async function seed() {
    for (const report of reports) {
        await adminDb.collection("reports").add({
            ...report,
            createdAt: FieldValue.serverTimestamp(),
        });
    }

    console.log(`✅ Added ${reports.length} reports.`);
}

seed()
    .then(() => process.exit(0))
    .catch((err) => {
        console.error(err);
        process.exit(1);
    });